name: Create Bug Report
description: Report a bug or crash in Impactor.
title: '[Bug] '
labels:
  - bug

body:
  - type: textarea
    id: text
    attributes:
      label: Report
    validations:
      required: true

  - type: checkboxes
    id: agreement
    attributes:
      label: Contributor Checks
      options:
        - label: I am willing to attempt to make a pull request to fix this bug
          required: false
